GRANT USAGE ON *.* TO 'vincent'@'localhost' IDENTIFIED BY PASSWORD '*5A416B3FCC143C6835BE623616B45D5F3876B4AF';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `gema\_radio`.* TO 'vincent'@'localhost';